name: django-tpl
services:
  database:
    image: postgres:13.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d:ro
      - postgres:/var/lib/postgresql/data

  mail:
    image: docker.io/mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "${SMTP_PORT:-1025}:1025"
      - "${SMTP_WEB_PORT:-8025}:8025"

  staticfiles:
    image: docker.io/nginx:1.29.3-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "${STATIC_PORT:-8080}:80"
    volumes:
      - ../staticfiles:/usr/share/nginx/:ro
      - ./nginx:/etc/nginx/conf.d/:ro

volumes:
  postgres:
    driver: local
